server:
  port: ${APPLICATION_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${APPLICATION_DB_URL:localhost}:${APPLICATION_DB_PORT:5432}/${APPLICATION_DB_NAME:invitation_core_db}
    username: ${APPLICATION_DB_USER:postgres}
    password: ${APPLICATION_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

service:
  ui:
    url: ${UI_APPLICATIONS:http://localhost:4200}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY:wipjd03kmv[wh567gmcvf2p0fh<niyedjgvdckjhkkhVvj;'\986546&*6865&^}
      token-duration-minutes: ${TOKEN_DURATION_MINUTES:600}
